name: "Test OCP addons"
description: "Testing OCP addons wheels with build123d and CadQuery"
inputs:
  os:
    description: "Operating system to use for the build"
    required: true
  python-version:
    description: "Python version to use for the build"
    required: true
  wheel-version:
    description: "Version of the wheel to build"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    # - - -

    - name: (Linux) Install ca-certificates
      if: runner.os == 'Linux'
      shell: bash -leo pipefail {0}
      run: |
        # (Linux) Install ca-certificates

        sudo apt-get update -qq  
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -qq ca-certificates > /dev/null 2>&1

   # - - -

    - name: Install MacOS Dependencies (x86_64 / arm64)
      if: runner.os == 'macOS'
      shell: bash -leo pipefail {0}
      run: |
        # Install MacOS Dependencies (x86_64 / arm64)

        brew install gsed
        # ensure gnu sed is in PATH before system (BSD) sed
        sudo ln -s "$(brew --prefix gnu-sed)/libexec/gnubin/sed" /usr/local/bin/sed

    # - - -
    
    - name: Prepare environment-test.yml
      shell: bash -leo pipefail {0}
      run: |
        # Prepare environment-test.yml

        sed -i 's/python=3\.1[0-9]/python=${{ inputs.python-version }}/' environment-test.yml

        cat environment-test.yml

    # - - -
    
    - name: Set up Python ${{ inputs.python-version }} via micromamba
      uses: mamba-org/setup-micromamba@v2
      with:
        environment-file: environment-test.yml
        log-level: warning
        init-shell: ${{ inputs.shells }}
        cache-environment: true
        cache-environment-key: environment-test-${{ inputs.python-version }}-${{ inputs.os }}

    # - - -

    - name: Download ocp-addons wheel
      uses: actions/download-artifact@v4
      with:
        name: ocp-addons-${{ inputs.wheel-version }}-wheel-${{ inputs.os }}-cp${{ inputs.python-version }}

    # - - -
    
    - name: Install OCP addons wheel
      shell: bash -leo pipefail {0}
      run: |
        # Install OCP addons wheel

        echo "$CONDA_PREFIX"

        pip install ocp_addons-*.whl
        pip list

        python -c "import OCP; print('Success: OCP', OCP.__version__)"
        python -c "import ocp_addons; print('Success; ocp-addons serializer: OCP', ocp_addons.serializer._test())"

    # - - -

    - name: Run build123d tests
      shell: bash -leo pipefail {0}
      run: |
        # Run build123d tests

        echo "$CONDA_PREFIX"
        
        pip install build123d
        pip list
        
        pytest -v

        # micromamba run -n test-ocp-addons pip install build123d        
        # micromamba run -n test-ocp-addons pytest -v
