name: Build OCP Addons

on:
    workflow_dispatch:
    push:
        branches:
            - new_approach

jobs:
    addons-ubuntu:
        name: Build OCP addons for ${{ matrix.python-version }} on ${{ matrix.os }}
        runs-on: ubuntu-latest
        container:
            image: ubuntu:20.04
            options: --name ci-ubuntu-20 # needed for manylinux_3_31
        strategy:
            fail-fast: false
            matrix:
                os: ["ubuntu-22.04"]
                # python-version: ["3.10", "3.11", "3.12", "3.13"]
                python-version: ["3.12"]

        steps:
            - uses: actions/checkout@v4

            - name: Extract version from pyproject.toml
              id: get_version
              uses: SebRollen/toml-action@v1.2.0
              with:
                  file: "pyproject.toml"
                  field: "project.version"

            - name: Build SDKs
              id: build-ocp-addons
              uses: ./.github/actions/build-wheel
              with:
                  os: ${{ matrix.os }}
                  python-version: ${{ matrix.python-version }}
                  shells: "bash"
                  wheel-version: ${{ steps.get_version.outputs.value }}

    addons-win-mac:
        name: Build OCP addons for ${{ matrix.python-version }} on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: ["macos-13", "macos-15", "windows-2022"]
                # python-version: ["3.10", "3.11", "3.12", "3.13"]
                python-version: ["3.12"]
                include:
                    - os: "macos-15"
                      shells: "bash"
                    - os: "macos-13"
                      shells: "bash"
                    - os: "windows-2022"
                      shells: "bash cmd.exe"
        steps:
            - uses: actions/checkout@v4

            - name: Extract version from pyproject.toml
              id: get_version
              uses: SebRollen/toml-action@v1.2.0
              with:
                  file: "pyproject.toml"
                  field: "project.version"

            - name: Build SDKs
              id: build-ocp-addons
              uses: ./.github/actions/build-wheel
              with:
                  os: ${{ matrix.os }}
                  python-version: ${{ matrix.python-version }}
                  shells: ${{ matrix.shells }}
                  wheel-version: ${{ steps.get_version.outputs.value }}

    tests:
        name: Test OCP Addons on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        needs: [addons-ubuntu, addons-win-mac]

        strategy:
            fail-fast: false
            matrix:
                os: ["macos-13", "macos-15", "ubuntu-22.04", "windows-2022"]
                # python-version: ["3.10", "3.11", "3.12", "3.13"]
                python-version: ["3.12"]

        steps:
            - uses: actions/checkout@v4

            - name: Extract version from pyproject.toml
              id: get_version
              uses: SebRollen/toml-action@v1.2.0
              with:
                  file: "pyproject.toml"
                  field: "project.version"

            - name: Test OCP addons
              id: test-ocp-addons
              uses: ./.github/actions/test-wheel
              with:
                  os: ${{ matrix.os }}
                  python-version: ${{ matrix.python-version }}
                  wheel-version: ${{ steps.get_version.outputs.value }}
