name: Release OCP Addons

on:
    push:
        tags:
        - '*'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ["macos-13", "macos-15", "windows-2022"]
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4

      - name: Extract version from pyproject.toml
        id: get_version
        uses: SebRollen/toml-action@v1.2.0
        with:
          file: "pyproject.toml"
          field: "project.version"

      - name: Download ocp-addons wheel
        uses: actions/download-artifact@v4
        with:
          name: ocp-addons-${{ steps.get_version.outputs.value }}-wheel-${{ matrix.os }}-cp${{ matrix.python-version }}
          path: ./wheelhouse

      - name: Upload wheels to GitHub Release
        uses: softprops/action-gh-release@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          files: ./wheelhouse/*.whl